blueprint:
  name: Haustür öffnen
  description: Öffnet die Haustür bei Ankunft
  domain: automation
  input:
    arrival_sensor:
      name: Ankunft Sensoren
      description: Sensoren, die den Ankunftsstatus überwachen
      selector:
        entity:
          multiple: true
          domain: sensor

    open_permission_notification:
      name: Benachrichtigung für Öffnungsanfrage
      description: Benachrichtigung, die gesendet wird, um die Erlaubnis zum Öffnen der Tür zu fragen
      selector:
        device:
          integration: mobile_app  # Oder notify, je nach Verwendung

    door_lock_front:
      name: Haustür Schloss
      description: Bezeichner für die Haustür
      selector:
        entity:
          domain: lock

trigger:
  - platform: state
    entity_id: !input arrival_sensor
    from: "towards"
    to: "arrived"

condition:
  - condition: state
    entity_id: !input door_lock_front
    state: "unlocked"

action:
  - service: notify.mobile_app_your_device_name  # Ersetze durch den tatsächlich verfügbaren Notify-Service
    data:
      message: "Möchtest du, dass ich die Haustür öffne? (Geht 5 Min.)"
      title: "Bitte gedrückt halten!"
      data:
        actions:
          - action: "OPEN"
            title: "Öffnen"
          - action: "NO"
            title: "Nein"

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "OPEN"

  - choose:
      - conditions:
          - condition: state
            entity_id: !input door_lock_front
            state: "unlocked"
        sequence:
          # Hier wird die Haustür einfach entriegelt
          - service: lock.unlock
            target:
              entity_id: !input door_lock_front

mode: parallel
max: 2
